name: Docker Deploy
on:
  push:
    branches:
      - main
jobs:
  Build-Container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Bun Runtime
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun i

      - name: Lint
        run: bun lint

      - name: Prettify
        run: bun prettify

      - name: Build bot
        run: bun run build

      - name: Build Container
        run: docker build -t korosan .
