name: Docker Deploy
on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # Exclude pushes for existing tags
jobs:
  Test-Code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Bun Runtime
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun i

      - name: Prettify
        run: bun prettify

      - name: Lint
        run: bun lint
  Build-Container:
    runs-on: ubuntu-latest
    needs: Test-Code
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Bun Runtime
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun i

      - name: Build Container
        run: docker build -t sehgahtoh/korosan .

      - name: Docker Autenticaion
        run: docker login -u sehgahtoh -p $DOCKER_PASSWORD
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Container
        run: docker push sehgahtoh/korosan:latest
  Create-Release:
    runs-on: ubuntu-latest
    needs: Build-Container
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create new tag
        run: |
          # Fetch tags from the remote
          git fetch --tags
          # Get the latest tag
          LAST_TAG=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          echo "Last tag: $LAST_TAG"
          
          # Increment the version
          VERSION=$(echo $LAST_TAG | awk -F. -v OFS=. '{$NF++;print}')
          echo "New tag: $VERSION"

          # Create a new tag and push it
          git tag $VERSION
          git push origin $VERSION

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
