name: Docker Deploy
on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # Exclude pushes for existing tags
jobs:
  Test-Code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Bun Runtime
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun i

      - name: Prettify
        run: bun prettify

      - name: Lint
        run: bun lint
  Build-Container:
    runs-on: ubuntu-latest
    needs: Test-Code
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Bun Runtime
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun i

      - name: Build Container
        run: docker build -t sehgahtoh/korosan .

      - name: Docker Autenticaion
        run: docker login -u sehgahtoh -p $DOCKER_PASSWORD
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Container
        run: docker push sehgahtoh/korosan:latest
